name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: setup-qemu-action
        uses: docker/setup-qemu-action@v1
      - name: Log in to Docker Hub
        uses: docker/login-action
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Deploy images
        run: |
          docker build -t postgres_backup
          docker tag postgres_backup:latest public.ecr.aws/p3h0z8x3/postgres-backup:12.9
          docker tag postgres_backup:latest overviewai/postgres-backup:12.9
          docker push public.ecr.aws/p3h0z8x3/postgres-backup:12.9
          docker push overviewai/postgres-backup:12.9
